### PR TITLE
Rewrite script.

### PR DESCRIPTION
**Pull request by stevefalco**
New version allows both tagged and nightly builds.

I was not easily able to clean up the previous messed up repo, so I just deleted it and started over.

Please pull my "new_script" branch into the master.  As of right now, it says "able to merge" and "can be automatically merged".

### CODE REVIEW

**Comment by aimylios** [comment]
Looks good!
To repeat my question from PR #9 (which probably got lost in the edit): Is it correct, that you dropped the "nightlies" suffix from the Release tag. Why? This would change the version number of the Copr builds, and it might break automatic updates (although I didn't actually test it).

**Comment by stevefalco** [comment]
I did miss your question - sorry.  But I don't think it will have any impact, because the first part of the version is "r" followed by a monotonically incrementing number, so the new builds should still look newer than the old builds.

**Comment by aimylios** [comment]
@stevefalco: OK, that sounds plausible. Thanks for checking!

@nickoe: These scripts do not yet generate separate RPMs for the libraries. They use the upper case "D" in packages3D because that is how the repository is called.

**Comment by nickoe** [comment]
Ahh, ok. Good. So this should be safe to merge?

**Comment by aimylios** [comment]
I think so (but I have not build-tested it). The only user visible change will be a new version numbering and that the "nightlies" tag is not part of the RPM name any more. And you will need to teach the server which takes care of triggering the automated builds how to use the new scripts.

**Comment by stevefalco** [comment]
As to teaching jenkins to use the new scripts, it is safe not to change anything, because the extraneous "rm -fr" lines won't actually remove anything (as those files are now under the build/rpmbuild/SOURCES dir), and because the nightlies.sh script no longer looks at any arguments from the command line.

However, in the interest of completeness, and to avoid confusion for any future maintainers, the jenkins script should eventually be simplified to:

```
git fetch
git checkout remotes/origin/master
# go nightlies go!
./nightlies.sh
```

**Comment by nickoe** [comment]
@stevefalco Yes, I know. I did review your patch after all. :)  I may decide to remove the `nightlies.sh` and just call `builder.sh` in the future.

**Pull request merged**
